"""initial_schema

Revision ID: e46dd1165378
Revises: 
Create Date: 2026-04-19 18:19:08.485333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e46dd1165378'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomalies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('candle_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('type', sa.Enum('volume_spike', 'price_swing', name='anomalytype'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='severity'), nullable=False),
    sa.Column('zscore', sa.Float(), nullable=True),
    sa.Column('iqr_flag', sa.Boolean(), nullable=False),
    sa.Column('report_status', sa.Enum('pending', 'completed', 'failed', name='reportstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_data',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('open', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('time', 'ticker')
    )
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('anomaly_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['anomaly_id'], ['anomalies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anomaly_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    op.drop_table('market_data')
    op.drop_table('anomalies')
    # ### end Alembic commands ###
